// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-wA4mKTy5R8kXguREycIMgpsyrJGc0A',
    appId: '1:405025216871:web:863885da0285010658f7c2',
    messagingSenderId: '405025216871',
    projectId: 'stint-manager-6cc16',
    authDomain: 'stint-manager-6cc16.firebaseapp.com',
    storageBucket: 'stint-manager-6cc16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbFCGV12fNkq2qvQgY_yp7nZnx3Ka27CY',
    appId: '1:405025216871:android:e2e58eea6062b33c58f7c2',
    messagingSenderId: '405025216871',
    projectId: 'stint-manager-6cc16',
    storageBucket: 'stint-manager-6cc16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlSbKR0eOOj07dwMYMbyXxORBuDLUI9RQ',
    appId: '1:405025216871:ios:569b4868e5b98e4058f7c2',
    messagingSenderId: '405025216871',
    projectId: 'stint-manager-6cc16',
    storageBucket: 'stint-manager-6cc16.appspot.com',
    iosClientId: '405025216871-9j21cnud1ulmam6aq1ss6da6bmu1qkj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.stintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlSbKR0eOOj07dwMYMbyXxORBuDLUI9RQ',
    appId: '1:405025216871:ios:992c63bd70be73f558f7c2',
    messagingSenderId: '405025216871',
    projectId: 'stint-manager-6cc16',
    storageBucket: 'stint-manager-6cc16.appspot.com',
    iosClientId: '405025216871-e7q0tqtt6p1eo5808mrk9g5gka22lmqv.apps.googleusercontent.com',
    iosBundleId: 'com.stint.stintApp',
  );
}
